[package]
name = "gpucomputehello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"

bevy.workspace = true
bevy-inspector-egui.workspace = true
rand = "0.8.5"
